[project]
name = "tojioo-passthrough"
version = "1.1.0"
description = "Typed nodes for ComfyUI to reduce wire clutter"
license = {file = "LICENSE"}
requires-python = ">=3.10"
readme = "README.md"

[project.urls]
Repository = "https://github.com/Tojioo/tojioo_passthrough"
Documentation = "https://github.com/Tojioo/tojioo_passthrough/wiki" # Will do if needed.
"Bug Tracker" = "https://github.com/Tojioo/tojioo_passthrough/issues"

[tool.comfy]
PublisherId = "tojioo"
DisplayName = "Tojioo Passthrough"
Icon = "https://avatars.githubusercontent.com/u/132622614?s=256"
includes = []
# requires-comfyui = ">=1.0.0"

# [project.classifiers]
# "Operating System :: OS Independent" = true
# "Environment :: GPU :: NVIDIA CUDA" = true
